#!/bin/bash

#-------------------#
#----- Helpers -----#
#-------------------#

usage() {
    echo "$0 [COMMAND] [ARGUMENTS]"
    echo "  Commands:"
    echo "  - up: rebuild and start all containers"
    echo "  - up-no-recreate: start all containers and print new container names"
    echo "  - start: start all containers"
    echo "  - stop: stop all containers"
    echo "  - run: run command on node node"
    echo "  - ipfs: run ipfs command"
    echo "  - ipfs-clear: clear ipfs storage"
    echo "  - es-proxy: run ES proxy"
    echo "  - es-reset: resets ES"
    echo "  - es-update: updates ES mappings"
    echo "  - eth-listener: run eth listener"
    echo "  - gulp: run gulp command"
    echo "  - test <docker-machine-name>: run tests"
    echo "  - update-config: updates config.js"
    echo "  - init <docker-machine-name>: builds app, clears IPFS and resets ES etc"
    echo "  - update: builds app, installs dependencies (no data removal)"
    echo "  - install-deps: install dependencies"
    echo "  - relese: make a release"
}

fn_exists() {
    type $1 2>/dev/null | grep -q 'is a function'
}

COMMAND=$1
shift
ARGUMENTS="${@}"

#--------------------#
#----- Commands -----#
#--------------------#

up() {
    docker-compose up -d --build --remove-orphans;
}

stop() {
    docker-compose stop;
}

up-no-recreate() {
    docker-compose up -d --no-build --no-recreate;
}

start() {
    docker-compose start;
}

es-proxy() {
    docker-compose run --no-deps -p 9201:9201 repux-indexer-node npm run es-proxy ${@}
}

es-reset() {
    docker-compose run --no-deps --rm repux-indexer-node npm run es-reset -- ${@}
}

es-update() {
    docker-compose run --no-deps --rm repux-indexer-node npm run es-update -- ${@}
}

eth-listener() {
    docker-compose run --no-deps --rm repux-indexer-node npm run eth-listener
}

log-server() {
    docker-compose logs -f --tail 100 repux-indexer-node
}

ipfs() {
    docker-compose exec repux-indexer-ipfs ipfs ${@}
}

ipfs-clear() {
    REFS=`docker-compose exec repux-indexer-ipfs ipfs pin ls --type=recursive | cut -d' ' -f1 | tr '\n' ' '`
    if [ "$REFS" ]; then
        echo "removing files..."
        docker-compose exec repux-indexer-ipfs ipfs pin rm $REFS
        docker-compose exec repux-indexer-ipfs ipfs block rm -f $REFS
        docker-compose exec repux-indexer-ipfs ipfs repo gc
    else
        echo "no files to remove"
    fi
}

gulp() {
    docker-compose run --no-deps --rm repux-indexer-node node node_modules/gulp/bin/gulp.js ${@}
}

build() {
    gulp ${@}
    update-config ${@}
}

test() {
    MACHINE_NAME=$1
    shift
    init $MACHINE_NAME --env=test ${@}
    gulp test --env=test ${@}
}

install-deps() {
    docker-compose run --no-deps --rm repux-indexer-node yarn install
}

update-config() {
    docker-compose run --no-deps --rm repux-indexer-node npm run update-config -- ${@}
}

init() {
    MACHINE_NAME=${1:-workhq}
    shift
    docker-machine ssh $MACHINE_NAME sudo sysctl -w vm.max_map_count=262144
    install-deps
    update-config ${@}
    gulp ${@}
    es-reset ${@}
    ipfs-clear
    rm -f data/lastReadBlock.dat
}

update() {
    install-deps
    update-config ${@}
    gulp ${@}
    rm -f data/lastReadBlock.dat
    es-update ${@}
}

run() {
    docker-compose run --no-deps --rm repux-indexer-node ${@}
}

release() {
    docker-compose run --no-deps --rm repux-indexer-node npm run release ${@}
}

#---------------------#
#----- Execution -----#
#---------------------#

fn_exists $COMMAND
if [ $? -eq 0 ]; then
    $COMMAND "$ARGUMENTS"
else
    usage
fi
