data_product:
    properties:
        address:
            type: text
            fields:
                keyword:
                    type: keyword
                    normalizer: lowercase_normalizer
        ownerAddress:
            type: text
            fields:
                keyword:
                    type: keyword
                    normalizer: lowercase_normalizer
        sellerMetaHash:
            type: text
            fields:
                keyword:
                    type: keyword
                    normalizer: lowercase_normalizer
        title:
            type: text
            fields:
                keyword:
                    type: keyword
                    normalizer: lowercase_normalizer
        shortDescription:
            type: text
        fullDescription:
            type: text
        type:
            type: text
            fields:
                keyword:
                    type: keyword
                    normalizer: lowercase_normalizer
        category:
            type: text
            fields:
                keyword:
                    type: keyword
                    normalizer: lowercase_normalizer
        maxNumberOfDownloads:
            type: integer
        price:
            type: text
        termsOfUseType:
            type: text
            fields:
                keyword:
                    type: keyword
                    normalizer: lowercase_normalizer
        name:
            type: text
            fields:
                keyword:
                    type: keyword
                    normalizer: lowercase_normalizer
        size:
            type: long
        lastUpdateTimestamp:
            type: date
            format: epoch_second
