data_product:
    properties:
        address:
            type: text
            fields:
                keyword:
                    type: keyword
        ownerAddress:
            type: text
            fields:
                keyword:
                    type: keyword
        sellerMetaHash:
            type: text
            fields:
                keyword:
                    type: keyword
        title:
            type: text
            fields:
                keyword:
                    type: keyword
        shortDescription:
            type: text
        fullDescription:
            type: text
        type:
            type: text
            fields:
                keyword:
                    type: keyword
        category:
            type: text
            fields:
                keyword:
                    type: keyword
        maxNumberOfDownloads:
            type: integer
        price:
            type: text
        termsOfUseType:
            type: text
            fields:
                keyword:
                    type: keyword
        name:
            type: text
            fields:
                keyword:
                    type: keyword
        size:
            type: long
        lastUpdateTimestamp:
            type: date
            format: epoch_second
