_default_:
    dynamic_templates:
        -
            not_analyzed:
                match: '*'
                mapping:
                    type: '{dynamic_type}'
                    index: not_analyzed
        -
            date_time:
                match: '*_at'
                mapping:
                    type: 'epoch_second'
                    index: not_analyzed
