data_product:
    properties:
        title:
            type: text
        shortDescription:
            type: text
        fullDescription:
            type: text
        type:
            type: text
        category:
            type: text
        maxNumberOfDownloads:
            type: integer
        price:
            type: long
        termsOfUseType:
            type: text
        name:
            type: text
        size:
            type: long
